from selenium import webdriver
import time
username = input("请输入您的账号")
password = input("请输入您的密码")
chrome = webdriver.Chrome()
chrome.get('https://tieba.baidu.com/')
chrome.find_element_by_xpath('//div[@class = "u_menu_item"]/a').click()
time.sleep(2)
chrome.find_element_by_id('TANGRAM__PSP_10__footerULoginBtn').click()
time.sleep(1)
chrome.find_element_by_id('TANGRAM__PSP_10__userName').send_keys(username)
chrome.find_element_by_id('TANGRAM__PSP_10__password').send_keys(password)
time.sleep(3)
chrome.find_element_by_id('TANGRAM__PSP_10__submit').click()
time.sleep(1)
chrome.find_element_by_class_name('onekey_btn').click()
time.sleep(2)
chrome.find_element_by_xpath('//div [@class = "sign_detail_hd"]/a').click()
time.sleep(1)
chrome.find_element_by_class_name('dialogJclose').click()
time.sleep(5)
chrome.quit()